Repository TeamWalkary/front-end, pull requests merged in 2023-10, with the labels that each got.

#5 Feat/#4 landing page
  src/App.tsx
  src/GlobalStyle.tsx
  src/assests/logo.svg
  src/components/Landing/LandingView.tsx
  src/pages/Landing.tsx
Labels: feat, 르미

#8 [feat] 로그인 페이지 제작
  src/GlobalStyle.tsx
  src/assests/closeBtn.svg
  src/components/Landing/LandingView.tsx
  src/components/Login/LoginView.tsx
  src/pages/Login.tsx
Labels: feat, 르미

#10 Feat/#9 sign up page
  src/GlobalStyle.tsx
  src/assests/backArrow.svg
  src/components/CollectDiary/index.tsx
  src/components/CollectPin/index.tsx
  src/components/Common/index.tsx
  src/components/Login/LoginView.tsx
  src/components/Main/index.tsx
  src/components/SignUp/SignUpView.tsx
  src/pages/SignUp.tsx
Labels: feat, 르미

#15 Feat/#4 로그인 기능 구현
  .gitignore
  src/components/Login/Input.tsx
  src/components/Login/LoginData.tsx
  src/components/Login/LoginView.tsx
  src/hooks/useInputValue.tsx
Labels: feat, 앙꼬

#17 Feat/#3 map 생성
  .gitignore
  index.html
  package.json
  src/assests/currentLocation.svg
  src/assests/gps.svg
  src/components/Main/MapView.tsx
  yarn.lock
Labels: feat, 연어

#21 Feat/#4 회원가입 기능구현
  src/components/Common/Button.tsx
  src/components/Common/Input.tsx
  src/components/Login/LoginData.tsx
  src/components/Login/LoginView.tsx
  src/components/Login/SubmitForms.tsx
  src/components/SignUp/SignUpView.tsx
  src/components/SignUp/SubmitForms.tsx
Labels: feat, 앙꼬

#25 Feat/#18 pin draw
  src/assests/gpsBtn.svg
  src/assests/pinBtn.svg
  src/assests/pinDraw.svg
  src/components/Main/MainView.tsx
  src/components/Main/MapView.tsx
  src/pages/Main.tsx
Labels: feat, 연어

#26 Feat/#24 diary page UI
  src/assests/check.svg
  src/assests/picture.svg
  src/components/Common/Today.tsx
  src/components/Diary/WriteDiary.tsx
  src/components/Main/MainView.tsx
Labels: feat, 르미

#28 [fix] merge 충돌 해결에서 태그 잘못 삭제
  src/components/Main/MainView.tsx
Labels: fix, 르미

#31 Feat/#6 create pin modal
  src/App.tsx
  src/assests/closebutton.svg
  src/components/Main/CreatePinModal.tsx
  src/components/Main/MainView.tsx
  src/components/Main/MapView.tsx
  src/pages/Main.tsx
  src/store/atom.ts
Labels: 람진

#36 feat: 일기 모아보기 뷰 레이아웃
  src/components/CollectDiary/Nothing.tsx
  src/components/CollectDiary/index.tsx
  src/components/Common/Button.tsx
  src/components/Landing/LandingView.tsx
  src/components/Login/LoginView.tsx
  src/components/Login/SubmitForms.tsx
  src/components/Main/SideNav.tsx
  src/components/SignUp/SubmitForms.tsx
  src/pages/CollectDiary.tsx
Labels: feat, 앙꼬
